on:
  push:
    branches:
      - main

concurrency:
  group: openfn-deployment
  cancel-in-progress: false

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    permissions:
      contents: write
    steps:
      - name: openfn deploy
        uses: openfn/cli-deploy-action@v1.0.0
        with:
          secret_input: ${{ secrets.OPENFN_dc50a0d8_a4dd_434f_8ea3_70aaf0a2acaf_API_KEY }}
          config_path_input: 'openfn-dc50a0d8-a4dd-434f-8ea3-70aaf0a2acaf-config.json'
